@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.toolbelt.integration.anvil;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;