modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"

[[mods]]
modId="toolbelt"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.toolbelt]]
   modId="neoforge"
   type="required"
   versionRange="[21.1.10-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="sewingkit"
   type="optional"
   versionRange="[2.0.1,)"
   ordering="NONE"
   side="BOTH"
#[[dependencies.toolbelt]]
#    modId="controllable"
#    type="optional"
#    versionRange="[0.25,)"
#    ordering="AFTER"
#    side="BOTH"