modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"

[[mods]]
modId="toolbelt"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
authors="gigaherz"
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="toolbelt.mixins.json"

[[dependencies.toolbelt]]
   modId="neoforge"
   type="required"
   versionRange="[21.3.19-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   type="required"
   versionRange="[1.21.3,1.22)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="sewingkit"
   type="optional"
   versionRange="[2.1.0,)"
   ordering="NONE"
   side="BOTH"