@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.toolbelt.customslots;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;