@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.toolbelt.customslots;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;