@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.toolbelt.customslots.example;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;