@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.toolbelt.customslots.example;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;