@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.toolbelt.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;