@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.toolbelt.integration;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;